[build]
  # Tell Netlify to execute the compile step right inside the frontend directory
  base = "teamup-master/frontend"
  command = "npm run build"
  publish = "dist/frontend/browser"

[functions]
  # Tell Netlify to climb out of the frontend and grab the actual backend root
  directory = "../backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  status = 200
  force = true
  to = "/.netlify/functions/server/:splat"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"