[[build]
  base = "teamup-master/frontend"
  command = "npm run build"
  # MATCH: Points directly to the Angular 19 production browser folder
  publish = "dist/frontend/browser"

[functions]
  directory = "../backend/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  status = 200
  force = true
  to = "/.netlify/functions/server/:splat"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"