[build]
  # This installs the dependencies first, THEN builds your Angular site
  command = "npm install --prefix teamup-master/frontend && npm run build --prefix teamup-master/frontend"
  publish = "teamup-master/frontend/dist/frontend/browser"

[functions]
  directory = "teamup-master/backend"
  node_bundler = "esbuild"

[dev]
  port = 8888
  functions = "teamup-master/backend"
  publish = "teamup-master/frontend/dist/frontend/browser"

[[redirects]]
  from = "/api/*"
  status = 200
  force = true
  to = "/.netlify/functions/server/:splat"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"